"""-- PIA VISUALIZACION 

CREATE DATABASE IF NOT EXISTS BASE_AUTOS;
USE BASE_AUTOS;

SELECT BASE_AUTOS

-- Crear la tabla 'autos'
CREATE TABLE autos (
    ID INT PRIMARY KEY,
    ESTADO_AUTO ENUM('NUEVO', 'USADOS') NOT NULL,
    MARCA_AUTO VARCHAR(50) NOT NULL,
    NUM_CILINDROS INT NOT NULL
);

INSERT INTO autos (ID, AUNUEVOS_USADOS, AU_MARCA, NUM_CILINDROS) VALUES
(1, 'NUEVO', 'NISSAN', 6),
(2, 'USADOS', 'NISSAN', 4),
(3, 'NUEVO', 'CHEVROLET', 6),
(4, 'USADOS', 'VOLKSWAGEN', 4),
(5, 'USADOS', 'HONDA', 8),
(6, 'NUEVO', 'TOYOTA', 4),
(7, 'USADOS', 'FORD', 4),
(8, 'NUEVO', 'HYUNDAI', 6),
(9, 'USADOS', 'KIA', 6),
(10, 'USADOS', 'HONDA', 4);

INSERT INTO autos (ID, AUNUEVOS_USADOS, AU_MARCA, NUM_CILINDROS) VALUES
(11, 'NUEVO', 'TOYOTA', 6),
(12, 'USADOS', 'CHEVROLET', 6),
(13, 'USADOS', 'BMW', 8),
(14, 'NUEVO', 'FORD', 4),
(15, 'NUEVO', 'TOYOTA', 4),
(16, 'USADOS', 'KIA', 6),
(17, 'USADOS', 'MERCEDES-BENZ', 6),
(18, 'USADOS', 'NISSAN', 4),
(19, 'NUEVO', 'TESLA', 4),
(20, 'USADOS', 'JEEP', 6);

INSERT INTO autos (ID, AUNUEVOS_USADOS, AU_MARCA, NUM_CILINDROS) VALUES
(21, 'USADOS', 'TOYOTA', 6),
(22, 'NUEVO', 'NISSAN', 4),
(23, 'USADOS', 'FORD', 4),
(24, 'USADOS', 'HONDA', 6),
(25, 'NUEVO', 'BMW', 6),
(26, 'USADOS', 'MITSUBISHI', 6),
(27, 'USADOS', 'CHEVROLET', 4),
(28, 'NUEVO', 'TESLA', 6),
(29, 'USADOS', 'KIA', 6),
(30, 'USADOS', 'FORD', 4);

INSERT INTO autos (ID, AUNUEVOS_USADOS, AU_MARCA, NUM_CILINDROS) VALUES
(31, 'NUEVO', 'MITSUBISHI', 6),
(32, 'USADOS', 'HONDA', 6),
(33, 'USADOS', 'KIA', 4),
(34, 'NUEVO', 'VOLKSWAGEN', 4),
(35, 'USADOS', 'TOYOTA', 6),
(36, 'NUEVO', 'BMW', 8),
(37, 'USADOS', 'HYUNDAI', 6),
(38, 'USADOS', 'MERCEDES-BENZ', 8),
(39, 'USADOS', 'NISSAN', 4),
(40, 'USADOS', 'CHEVROLET', 6);

INSERT INTO autos (ID, AUNUEVOS_USADOS, AU_MARCA, NUM_CILINDROS) VALUES
(41, 'USADOS', 'FORD', 4),
(42, 'NUEVO', 'HONDA', 4),
(43, 'NUEVO', 'TOYOTA', 6),
(44, 'USADOS', 'JEEP', 6),
(45, 'USADOS', 'VOLKSWAGEN', 4),
(46, 'USADOS', 'MITSUBISHI', 6),
(47, 'NUEVO', 'BMW', 8),
(48, 'USADOS', 'MERCEDES-BENZ', 8),
(49, 'USADOS', 'HYUNDAI', 6),
(50, 'USADOS', 'HONDA', 6);

INSERT INTO autos (ID, AUNUEVOS_USADOS, AU_MARCA, NUM_CILINDROS) VALUES
(51, 'NUEVO', 'FORD', 4),
(52, 'USADOS', 'CHEVROLET', 4),
(53, 'NUEVO', 'JEEP', 6),
(54, 'USADOS', 'KIA', 4),
(55, 'NUEVO', 'MERCEDES-BENZ', 8),
(56, 'USADOS', 'NISSAN', 6),
(57, 'USADOS', 'TOYOTA', 6),
(58, 'NUEVO', 'BMW', 8),
(59, 'USADOS', 'HYUNDAI', 6),
(60, 'USADOS', 'TOYOTA', 6);

INSERT INTO autos (ID, AUNUEVOS_USADOS, AU_MARCA, NUM_CILINDROS) VALUES
(61, 'NUEVO', 'NISSAN', 6),
(62, 'USADOS', 'MITSUBISHI', 6),
(63, 'USADOS', 'FORD', 4),
(64, 'USADOS', 'HONDA', 4),
(65, 'USADOS', 'JEEP', 6),
(66, 'NUEVO', 'TOYOTA', 6),
(67, 'USADOS', 'NISSAN', 4),
(68, 'NUEVO', 'HYUNDAI', 4),
(69, 'USADOS', 'MERCEDES-BENZ', 8),
(70, 'USADOS', 'KIA', 4);

INSERT INTO autos (ID, AUNUEVOS_USADOS, AU_MARCA, NUM_CILINDROS) VALUES
(71, 'USADOS', 'HONDA', 6),
(72, 'NUEVO', 'MITSUBISHI', 6),
(73, 'USADOS', 'FORD', 6),
(74, 'USADOS', 'BMW', 8),
(75, 'USADOS', 'JEEP', 6),
(76, 'NUEVO', 'VOLKSWAGEN', 4),
(77, 'USADOS', 'MERCEDES-BENZ', 8),
(78, 'USADOS', 'HYUNDAI', 6),
(79, 'USADOS', 'CHEVROLET', 6),
(80, 'NUEVO', 'NISSAN', 4);

INSERT INTO autos (ID, AUNUEVOS_USADOS, AU_MARCA, NUM_CILINDROS) VALUES
(81, 'USADOS', 'TOYOTA', 6),
(82, 'NUEVO', 'MITSUBISHI', 4),
(83, 'USADOS', 'HONDA', 6),
(84, 'USADOS', 'VOLKSWAGEN', 4),
(85, 'NUEVO', 'CHEVROLET', 4),
(86, 'USADOS', 'FORD', 6),
(87, 'USADOS', 'KIA', 4),
(88, 'NUEVO', 'BMW', 8),
(89, 'USADOS', 'MERCEDES-BENZ', 8),
(90, 'USADOS', 'HONDA', 4);

INSERT INTO autos (ID, AUNUEVOS_USADOS, AU_MARCA, NUM_CILINDROS) VALUES
(91, 'NUEVO', 'VOLKSWAGEN', 4),
(92, 'USADOS', 'TOYOTA', 6),
(93, 'NUEVO', 'FORD', 4),
(94, 'USADOS', 'BMW', 6),
(95, 'USADOS', 'MERCEDES-BENZ', 8),
(96, 'USADOS', 'CHEVROLET', 4),
(97, 'NUEVO', 'HONDA', 6),
(98, 'USADOS', 'KIA', 4),
(99, 'USADOS', 'MERCEDES-BENZ', 8),
(100, 'USADOS', 'JEEP', 6);
"""